language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'

before_install: composer install
before_script: composer require phpunit
script: 
  phpunit --configuration $DB.phpunit.xml
  phpunit testfungsi_fungsi.php